name: "coverage"
on:
  push:
    branches: 
      - main

jobs:
  coverage-covidolog:
    runs-on: ubuntu-latest
    
    container:
      image:google/flutter:latest
    
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - uses: actions/checkout@v1
      - name: Collect coverage
        run: |
          flutter pub get
          flutter pub global activate test_coverage
          flutter pub global run test_coverage --exclude "**/js/**"
      - uses: codecov/codecov-action@v1.0.0	
        with:
          token: ${{ secrets.CODECOV_TOKEN }}	
          file: covidolog/coverage/lcov.info
